env:
    es6: true
    browser: true
    jest: true
plugins:
    - 'react-hooks'
settings:
    react:
        version: detect

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:react/recommended'
    - 'plugin:prettier/recommended'
    - 'prettier'
    - 'prettier/react'
    - 'prettier/@typescript-eslint'

rules:
    "@typescript-eslint/no-explicit-any": off